name: Deploy WSL Image

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install AzureAD Module
      shell: powershell
      run: |
        Install-Module -Name AzureAD -Scope CurrentUser -Force -AllowClobber

    - name: Install IntuneWin32App Module
      shell: powershell
      run: |
        Install-Module -Name IntuneWin32App -Scope CurrentUser -Force -ErrorAction Stop

    - name: Login to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload Package to Intune
      shell: powershell
      run: |
        Install-Module -Name Microsoft.Graph -Scope CurrentUser -Force -AllowClobber
        
        # Application properties
        $appFilePath = ".\exported.intunewin" # Ensure this path is correct
        $appName = "Ubuntu-Custom"
        $appDescription = "Custom Ubuntu WSL Image"
        $appPublisher = "DEVOPS-LSEG"
        $installCommand = "wsl --import Ubuntu C:\WSL\Ubuntu .\exported.tar"
        $uninstallCommand = "wsl --unregister Ubuntu"

        # Detection Rule
        $detectionRule = New-Object 'System.Collections.Specialized.OrderedDictionary'
        $detectionRule['detectionType'] = 'file'
        $detectionRule['path'] = "C:\\Program Files\\WSL"
        $detectionRule['fileName'] = "wsl.exe"
        $detectionRule['check32BitOn64System'] = $false
        $detectionRules = @($detectionRule)

        $DetectionRule = New-IntuneWin32AppDetectionRuleFile -Existence -FileOrFolder "wsl.exe" -Path "C:\\Program Files\\WSL" -Check32BitOn64System $false -DetectionType "exists"

        $RequirementRule = New-IntuneWin32AppRequirementRule -Architecture x64 -MinimumSupportedOperatingSystem 1909

        try {
            Add-IntuneWin32App -FilePath $appFilePath -DisplayName $appName -Description $appDescription -Publisher $appPublisher -InstallExperience "system" -RestartBehavior "suppress" -DetectionRule $DetectionRule -RequirementRule $RequirementRule -InstallCommandLine $installCommand -UninstallCommandLine $uninstallCommand -Verbose
        } catch {
            Write-Error "Error uploading the package to Intune: $_"
            exit 1
        }
