name: Deploy WSL Image

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install AzureAD Module
      shell: powershell
      run: |
        Install-Module -Name AzureAD -Scope CurrentUser -Force -AllowClobber
    - name: Login to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Run PowerShell Script
      shell: powershell
      run: |
        ./intune_upload.ps1 TenantId ${{ secrets.TENANTID }} -AppId ${{ secrets.APPID }} -AppSecret ${{ secrets.APPSECRET }}
        
