name: Deploy WSL Image

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Required PowerShell Modules
      shell: powershell
      run: |
        Install-Module -Name AzureAD -Scope CurrentUser -Force -AllowClobber
        Install-Module -Name Microsoft.Graph -Scope CurrentUser -Force -AllowClobber
        Install-Module -Name IntuneWin32App -Scope CurrentUser -Force -AllowClobber

    - name: Run PowerShell Script with Azure Credentials
      shell: powershell
      run: |
        ./intune_upload.ps1 -CredentialsJson '${{ secrets.AZURE_CREDENTIALS }}'
