name: Deploy WSL Image

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run PowerShell Script
      shell: pwsh
      run: |
        .\intune_upload.ps1 -TenantId ${{ secrets.TenantId }} -AppId ${{ secrets.AppId }} -AppSecret ${{ secrets.AppSecret }}
